In [52]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
from keras.preprocessing.sequence import TimeseriesGenerator

In [53]:
data = pd.read_csv("data.csv")
data

Date  Queries        Area
0   01/03/2022       55  Anna nagar
1   02/03/2022       60  Anna nagar
2   03/03/2022       57  Anna nagar
3   04/03/2022       45  Anna nagar
4   05/03/2022       85  Anna nagar
..         ...      ...         ...
56  03/03/2022       24  Anna nagar
57  25/03/2022       70  Anna nagar
58  04/04/2022       81  Anna nagar
59  28/03/2022       88  Anna nagar
60  18/04/2022       54  Anna nagar

[61 rows x 3 columns]

In [54]:
read_data = data.iloc[0:31]
read_data.index.freq = 'D'

In [55]:
read_data.drop(columns=["Area"],inplace=True)
read_data.set_index(["Date"],inplace=True)

C:\Users\jishn\AppData\Local\Temp\ipykernel_17108\2196445711.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  read_data.drop(columns=["Area"],inplace=True)


In [59]:
train = read_data.iloc[:28]
test = read_data.iloc[28:]



Queries
Date               
29/03/2022       97
30/03/2022       75
31/03/2022       56

In [60]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [61]:
scaler.fit(train)
scaled_train = scaler.transform(train)
scaled_test = scaler.transform(test)

In [62]:
n_input = 3
n_features = 1
generator = TimeseriesGenerator(scaled_train, scaled_train, length=n_input, batch_size=1)

In [63]:
X,y = generator[0]
print(f'Given the Array: \n{X.flatten()}')
print(f'Predict this y: \n {y}')     

Given the Array: 
[0.53012048 0.59036145 0.55421687]
Predict this y: 
 [[0.40963855]]


In [64]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [65]:
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(n_input, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [66]:
model.fit(generator,epochs=50)

Epoch 1/50
25/25 [==============================] - 4s 8ms/step - loss: 0.3060
Epoch 2/50
25/25 [==============================] - 0s 6ms/step - loss: 0.1500
Epoch 3/50
25/25 [==============================] - 0s 6ms/step - loss: 0.0927
Epoch 4/50
25/25 [==============================] - 0s 6ms/step - loss: 0.0805
Epoch 5/50
25/25 [==============================] - 0s 5ms/step - loss: 0.0843
Epoch 6/50
25/25 [==============================] - 0s 5ms/step - loss: 0.0824
Epoch 7/50
25/25 [==============================] - 0s 5ms/step - loss: 0.0883
Epoch 8/50
25/25 [==============================] - 0s 6ms/step - loss: 0.0814
Epoch 9/50
25/25 [==============================] - 0s 6ms/step - loss: 0.0811
Epoch 10/50
25/25 [==============================] - 0s 5ms/step - loss: 0.0802
Epoch 11/50
25/25 [==============================] - 0s 6ms/step - loss: 0.0815
Epoch 12/50
25/25 [==============================] - 0s 5ms/step - loss: 0.0808
Epoch 13/50
25/25 [==============================

In [67]:
last_train_batch = scaled_test
last_train_batch = last_train_batch.reshape((1, n_input, n_features))
last_train_batch

array([[[1.03614458],
        [0.77108434],
        [0.54216867]]])

In [68]:
model.predict(last_train_batch)


1/1 [==============================] - 1s 528ms/step


array([[0.5196684]], dtype=float32)

In [69]:
scaler.inverse_transform([[0.5196684]])

array([[54.1324772]])